#!/usr/bin/env bash
set -euo pipefail

# Reads the live PayKassa gateway settings from this WordPress site's
# database (via WP-CLI, read-only) and writes them into a local, gitignored
# .env file for tools/probe_paykassa_merchant_connectivity.php.
#
# Never prints secret values to the terminal. Never modifies the database.

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WP_PATH="${WP_PATH:-$(cd "$BASE_DIR/../../.." && pwd)}"

if [[ ! -f "$WP_PATH/wp-load.php" ]]; then
    echo "WordPress root not found at: $WP_PATH" >&2
    echo "Set WP_PATH=/path/to/wordpress and rerun, e.g.:" >&2
    echo "  WP_PATH=/var/www/html bash scripts/export-merchant-env.sh" >&2
    exit 1
fi

if ! command -v wp >/dev/null 2>&1; then
    echo "WP-CLI ('wp') is required but was not found in PATH." >&2
    exit 1
fi

SETTINGS_JSON="$(wp option get woocommerce_paykassa_settings --format=json --path="$WP_PATH" 2>/dev/null || true)"

if [[ -z "$SETTINGS_JSON" ]]; then
    echo "Could not read the 'woocommerce_paykassa_settings' option. Is PayKassa configured on this site?" >&2
    exit 1
fi

ENV_FILE="$BASE_DIR/.env"

php -r '
$settings = json_decode($argv[1], true);
if (!is_array($settings)) {
    fwrite(STDERR, "Could not parse gateway settings JSON.\n");
    exit(1);
}
$existing = array();
if (is_file($argv[2])) {
    foreach (file($argv[2], FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: array() as $line) {
        $line = trim($line);
        if ($line === "" || $line[0] === "#" || strpos($line, "=") === false) {
            continue;
        }
        [$k, $v] = explode("=", $line, 2);
        $existing[trim($k)] = $v;
    }
}
$map = array(
    "PAYKASSA_SANDBOX_SHOP_ID" => (string) ($settings["shop_id"] ?? ""),
    "PAYKASSA_SANDBOX_SHOP_PASSWORD" => (string) ($settings["shop_password"] ?? ""),
    "PAYKASSA_SANDBOX_API_ID" => (string) ($settings["api_id"] ?? ""),
    "PAYKASSA_SANDBOX_API_PASSWORD" => (string) ($settings["api_password"] ?? ""),
);
$public_url = $existing["PAYKASSA_PUBLIC_SITE_URL"] ?? "";
if ($public_url === "") {
    $external = is_string($settings["external_base_url"] ?? null) ? rtrim($settings["external_base_url"], "/") : "";
    $public_url = $external;
}
$map["PAYKASSA_PUBLIC_SITE_URL"] = $public_url;
foreach (array("PAYKASSA_PROBE_SYSTEM_ID", "PAYKASSA_PROBE_CURRENCY", "PAYKASSA_PROBE_AMOUNT") as $passthrough) {
    $map[$passthrough] = $existing[$passthrough] ?? "";
}
$lines = array(
    "# Generated by scripts/export-merchant-env.sh from the live database settings.",
    "# Gitignored. Never commit this file.",
);
foreach ($map as $k => $v) {
    $lines[] = $k . "=" . $v;
}
file_put_contents($argv[2], implode("\n", $lines) . "\n");
chmod($argv[2], 0600);
$written = array();
foreach ($map as $k => $v) {
    $written[] = $k . ($v === "" ? " (empty)" : " (set)");
}
fwrite(STDERR, "Wrote " . $argv[2] . ":\n  " . implode("\n  ", $written) . "\n");
' "$SETTINGS_JSON" "$ENV_FILE"

echo "Done. Review $ENV_FILE, then run: php tools/probe_paykassa_merchant_connectivity.php"
